<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.x2NVyfz' shared service.

return $this->privates['.service_locator.x2NVyfz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'PasswordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'PasswordEncoder' => '?',
    'entityManager' => '?',
    'profilRepository' => 'App\\Repository\\ProfilRepository',
    'serializer' => '?',
]);
