<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNK11Xyf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNK11Xyf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNK11Xyf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNK11Xyf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNK11Xyf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NK11Xyf',
    'container.build_id' => '3a719880',
    'container.build_time' => 1567711174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNK11Xyf');
