<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HOv7.f3' shared service.

return $this->privates['.service_locator.HOv7.f3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthController::login' => ['privates', '.service_locator.y8wMjBn', 'get_ServiceLocator_Y8wMjBnService.php', true],
    'App\\Controller\\SystemeController::addprest' => ['privates', '.service_locator.x2NVyfz', 'get_ServiceLocator_X2NVyfzService.php', true],
    'App\\Controller\\SystemeController::addsys' => ['privates', '.service_locator.x2NVyfz', 'get_ServiceLocator_X2NVyfzService.php', true],
    'App\\Controller\\AuthController:login' => ['privates', '.service_locator.y8wMjBn', 'get_ServiceLocator_Y8wMjBnService.php', true],
    'App\\Controller\\SystemeController:addprest' => ['privates', '.service_locator.x2NVyfz', 'get_ServiceLocator_X2NVyfzService.php', true],
    'App\\Controller\\SystemeController:addsys' => ['privates', '.service_locator.x2NVyfz', 'get_ServiceLocator_X2NVyfzService.php', true],
], [
    'App\\Controller\\AuthController::login' => '?',
    'App\\Controller\\SystemeController::addprest' => '?',
    'App\\Controller\\SystemeController::addsys' => '?',
    'App\\Controller\\AuthController:login' => '?',
    'App\\Controller\\SystemeController:addprest' => '?',
    'App\\Controller\\SystemeController:addsys' => '?',
]);
